stages:
  - build
  - test

# Stage: Build
build:
  stage: build
  script:
    - echo "Building the Docker image..."
    - docker-compose -f docker-compose.test.yml build
  tags:
    - docker

# Stage: Test
test:
  stage: test
  services:
    - docker:19.03.12-dind
  script:
    - echo "Running tests..."
    - docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from app
  after_script:
    - docker-compose -f docker-compose.test.yml down
  tags:
    - docker
