# docker-compose.yml
name: translation-tool-prod

services:
  libretranslate:
    container_name: libretranslate
    build:
      context: .
      dockerfile: docker/Dockerfile.lt  
    image: translationtool/libretranslate
    restart: unless-stopped
    volumes:
      - libretranslate-models:/home/libretranslate/.local:rw  
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://libretranslate:5000/languages || exit 1"]
      interval: 10s
      retries: 999
      start_period: 10s
      timeout: 5s
    networks:
      - translationtool

  flask:
    container_name: flask
    build:
      context: .                    
      dockerfile: docker/Dockerfile.prod  
    image: translationtool/flask
    ports:
      - "80:5000"                     # Extern Port 80, intern Port 80 (entspricht deinem CMD in Dockerfile.prod)
    env_file:
      - env/prod.env                
    environment:
      - FLASK_APP=app               # Falls benötigt als Fallback, wird aber meist über .env gesetzt
      - FLASK_ENV=production
    depends_on:
      libretranslate:
        condition: service_healthy  
    networks:
      - translationtool

volumes:
  libretranslate-models:
    name: libretranslate-models

networks:
  translationtool:
