# docker-compose.yml for production
name: translation-tool-prod

services:
  libretranslate:
    container_name: libretranslate
    build:
      context: .
      dockerfile: docker/Dockerfile.lt
    image: translationtool/libretranslate
    restart: unless-stopped
    volumes:
      - libretranslate-models:/home/libretranslate/.local:rw  # Persist language models
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://libretranslate:5000/languages || exit 1"]
      interval: 10s
      retries: 999
      start_period: 10s
      timeout: 5s
    networks:
      - translationtool

  flask:
    container_name: flask
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    image: translationtool/flask
    working_dir: /workspace
    ports:
      - "80:5000"  # Expose app on external port 80
    env_file:
      - env/prod.env
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
    depends_on:
      libretranslate:
        condition: service_healthy
    networks:
      - translationtool

volumes:
  libretranslate-models:
    name: libretranslate-models

networks:
  translationtool:
