# docker/Dockerfile.prod
FROM python:3.12-slim

WORKDIR /workspace/app

COPY app/requirements.txt /workspace/app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ /workspace/app

EXPOSE 5000

CMD ["gunicorn", "-k", "eventlet", "-w", "1", "-b", "0.0.0.0:5000", "wsgi:app"]