# docker/Dockerfile.dev
FROM python:3.12-slim

WORKDIR /workspace/app

COPY app/requirements.txt /workspace/app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt pytest

EXPOSE 5000

CMD ["python", "app.py"]
