# docker/Dockerfile.test

FROM python:3.12-slim

WORKDIR /workspace

ENV PYTHONPATH=/workspace/app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt pytest coverage pytest-cov

COPY app/ app/
COPY tests/ tests/
COPY env/test.env env/test.env

CMD ["pytest", "--rootdir=tests", "--cov=app", "--cov-report=term-missing", "tests/"]