# Docker Compose for development

name: translation-tool-dev

services:
  libretranslate:
    container_name: libretranslate-dev
    
  flask:
    container_name: flask-dev
    build: 
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/workspace/app:rw # code mounted into container
      - ./tests:/workspace/tests:rw # tests mounted into container
      - ./.vscode:/workspace/.vscode:rw # vscode mounted into container
    environment:
      - FLASK_ENV = development